env: "local" #local, dev, prod 
storage_path: "./internal/data/wallet.db"
http_server:
  address: "localhost:8088"
  timeout: 4s #время на обработку одного запроса
  idle_timeout: 60s #время соединения с клиентом (время которое мы ждем от клиента. Если превышен - обрываем)