env: "dev" #local, dev, prod 
db_server:
  host: "0.0.0.0"
  port: 5432
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s #время на обработку одного запроса
  idle_timeout: 60s #время соединения с клиентом (время которое мы ждем от клиента. Если превышен - обрываем)
kafka:
  brokers:
    - "kafka:9092"
    - "kafka2:9093"
    - "kafka3:9094"
  topic: "wallet_events"