env: "local" #local, dev, prod 
db_server:
  host: "localhost"
  port: 5430
http_server:
  address: "localhost:8082"
  timeout: 4s #время на обработку одного запроса
  idle_timeout: 60s #время соединения с клиентом (время которое мы ждем от клиента. Если превышен - обрываем)
kafka:
  brokers:
    - "localhost:29092"
    - "localhost:29093"
    - "localhost:29094"
  topic: "wallet_events"